name: CI

on:
  push:
    branches: [ main, refactor/ecommerce-entities ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pytest coverage
      - name: Lint with flake8
        run: flake8 .
      - name: Lint with pylint
        run: pylint ecommerce_refatorado || true
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v
      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
